#!/bin/sh

if [ -z ${SEED+x} ]; 
	then SEED="time"; 
# else 
	# echo "SEED is set to '$SEED'"; 
fi

start=`date +%s.%N`

./kima -t 4 -s $SEED

e=$? # the return code of the last command

end=`date +%s.%N`

#runtime=$((end-start))
runtime=$( echo "$end - $start" | bc -l )
echo 
echo Took $runtime seconds

exit $e